// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqwwtnUMYRq-tvJwMzw8JBduiCDaTJqHo',
    appId: '1:946454886196:web:9c7af53c1fe3ba60fbd761',
    messagingSenderId: '946454886196',
    projectId: 'flutter-ai-playground-f355e',
    authDomain: 'flutter-ai-playground-f355e.firebaseapp.com',
    storageBucket: 'flutter-ai-playground-f355e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqU6CsECogSGeYZr8WUokp02OAM-Y2kk0',
    appId: '1:946454886196:android:e20459236b5a3da7fbd761',
    messagingSenderId: '946454886196',
    projectId: 'flutter-ai-playground-f355e',
    storageBucket: 'flutter-ai-playground-f355e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2AnJVPAlXLNotfdEkmJt1QP3TfUyAwNk',
    appId: '1:946454886196:ios:1fc38b4a54ea1330fbd761',
    messagingSenderId: '946454886196',
    projectId: 'flutter-ai-playground-f355e',
    storageBucket: 'flutter-ai-playground-f355e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2AnJVPAlXLNotfdEkmJt1QP3TfUyAwNk',
    appId: '1:946454886196:ios:1fc38b4a54ea1330fbd761',
    messagingSenderId: '946454886196',
    projectId: 'flutter-ai-playground-f355e',
    storageBucket: 'flutter-ai-playground-f355e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqwwtnUMYRq-tvJwMzw8JBduiCDaTJqHo',
    appId: '1:946454886196:web:12b72fa865e1f1b7fbd761',
    messagingSenderId: '946454886196',
    projectId: 'flutter-ai-playground-f355e',
    authDomain: 'flutter-ai-playground-f355e.firebaseapp.com',
    storageBucket: 'flutter-ai-playground-f355e.firebasestorage.app',
  );
}
